pipeline {
    agent { node { label 'Agent-1' } }
    options {
        ansiColor('xterm')
    }
    
    stages {
        stage('init') {
            steps {
                sh '''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform plan
                '''
            }
        }
    }

    post { 
        always { 
            echo 'I will always run whether the job is a success or not'
        }
        success { 
            echo 'I will run only when the job is a success'
        }
        failure { 
            echo 'I will run when there is a failure'
        }
    }
}
